routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// home page
Route::get('/', "ProductsController@index")->name('home');

// dashboard
Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/pages', "Admin\PagesController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/users', "Admin\UsersController", ['except' => ['show'], 'as' => 'admin']);
    // shop
    Route::resource('/products', "Admin\ProductsController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/categories', "Admin\CategoriesController", ['except' => ['show'], 'as' => 'admin']);
});

// sign up
Route::get('/sign-up', "UsersController@signUp");
Route::post('/sign-up', "UsersController@store");

// sign in
Route::get('/sign-in', "LoginController@create")->name('login');
Route::post('/sign-in', "LoginController@store");
Route::delete('/logout', "LoginController@destroy");

Route::resource('products', "ProductsController", ['only' => ['index', 'show']]);
Route::resource('categories', "CategoriesController", ['only' => ['index', 'show']]);
Route::get('{page}', "PagesController@show")->name('pages.show');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function groups()
    {
        return $this->belongsToMany(UserGroup::class);
    }

    public function isAdmin()
    {
        foreach ($this->groups as $group) {
            if ($group->name == 'admin') {
                return true;
            }
        }
        return false;
    }

    public function getAssignedGroupsList()
    {
        $list = [];
        foreach ($this->groups as $group) {
            $list[] = $group->name;
        }
        return implode(', ', $list);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\UserGroup;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with(compact('users'));
    }

    public function create()
    {
        $groups = UserGroup::all();
        return view('admin.users.create')->with(compact('groups'));
    }

    public function store(Request $request)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\SignUpUserRequest;
use App\User;
use App\UserGroup;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest');
    }

    public function signUp()
    {
        return view('users.sign-up');
    }

    public function store(SignUpUserRequest $request)
    {
        DB::transaction(function() use ($request) {
            $user = User::create($request->all(['email','name']) + ['password' => bcrypt($request->post('password'))]);
            Auth::login($user);

            $group = UserGroup::where('name', 'client')->first();
            $user->groups()->attach($group);
        });

        return redirect()->route('home');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layout.base')

@section('top')
    <h1 class="h2">Add new user</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            @include('partials.errors')
            <form action="{{ route('admin.users.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" value="{{ old('name') }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" name="email" id="email" value="{{ old('email') }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="groups">User Groups:</label>
                    <select name="groups" id="groups"  class="form-control" multiple>
                        @foreach($groups as $group)
                            <option value="{{ $group->id }}">{{ $group->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" value="{{ old('password') }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="password_confirmation">Password Conformation:</label>
                    <input type="password" name="password_confirmation" id="password_confirmation"
                           value="{{ old('password_confirmation') }}" class="form-control">
                </div>

                <div class="form-group">
                    <button class="btn btn-success">Sign up</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout.base')

@section('top')
    <h1 class="h2">Users</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{ route('admin.users.create') }}" class="btn btn-sm btn-outline-success">Add new</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Groups</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->getAssignedGroupsList() }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-sm btn-outline-primary ml-1">Edit</a>
                                <form action="{{ route('admin.users.destroy', $user->id) }}" method="post" class="d-block">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-outline-danger ml-1">Remove</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="text-danger">no users</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
@endsection