routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// home page
Route::get('/', "ProductsController@index")->name('home');

// dashboard
Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/pages', "Admin\PagesController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/users', "Admin\UsersController", ['except' => ['show'], 'as' => 'admin']);
    // shop
    Route::resource('/products', "Admin\ProductsController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/categories', "Admin\CategoriesController", ['except' => ['show'], 'as' => 'admin']);
});

// sign up
Route::get('/sign-up', "UsersController@signUp");
Route::post('/sign-up', "UsersController@store");

// sign in
Route::get('/sign-in', "LoginController@create")->name('login');
Route::post('/sign-in', "LoginController@store");
Route::delete('/logout', "LoginController@destroy");

Route::resource('products', "ProductsController", ['only' => ['index', 'show']]);
Route::resource('categories', "CategoriesController", ['only' => ['index', 'show']]);
Route::get('{page}', "PagesController@show")->name('pages.show');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = ['name', 'slug'];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function products()
    {
        return $this->hasMany(Product::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Category;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index')->with(compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(StoreCategoryRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('admin.categories.index')->with('success', 'Created successfully');
    }

    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    public function update(Category $category, UpdateCategoryRequest $request)
    {
        $category->update($request->all());
        return redirect()->route('admin.categories.index')->with('success', 'Updated successfully');
    }

    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.categories.index')->with('success', 'Removed successfully');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('categories.index')->with(compact('categories'));
    }

    public function show(Category $category)
    {
        return view('categories.show')->with(compact('category'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout.base')

@section('top')
    <h1 class="h2">Add new category</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            @include('partials.errors')
            <form action="{{ route('admin.categories.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" value="{{ old('name') }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="slug">Slug:</label>
                    <input type="text" name="slug" id="slug" value="{{ old('slug') }}" class="form-control">
                </div>

                <div class="form-group">
                    <button class="btn btn-success">Add</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout.base')

@section('top')
    <h1 class="h2">Edit category</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            @include('partials.errors')
            <form action="{{ route('admin.categories.update', $category->slug) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" name="name" id="name" value="{{ $category->name }}" class="form-control">
                </div>

                <div class="form-group">
                    <label for="slug">Slug:</label>
                    <input type="text" name="slug" id="slug" value="{{ $category->slug }}" class="form-control">
                </div>

                <div class="form-group">
                    <button class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout.base')

@section('top')
    <h1 class="h2">Categories</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{ route('admin.categories.create') }}" class="btn btn-sm btn-outline-success">Add new</a>
        </div>
    </div>
@endsection

@section('content')
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->name }}</td>
                        <td>{{ $category->slug }}</td>
                        <td>
                            <div class="btn-group">
                                <a target="_blank" href="{{ route('categories.show', $category->slug) }}" class="btn btn-sm btn-outline-primary">View on site</a>
                                <a href="{{ route('admin.categories.edit', $category->slug) }}" class="btn btn-sm btn-outline-primary ml-1">Edit</a>
                                <form action="{{ route('admin.categories.destroy', $category->slug) }}" method="post" class="d-block">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-outline-danger ml-1">Remove</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="text-danger">no categories</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
@endsection