routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// home page
Route::get('/', "ProductsController@index")->name('home');

// dashboard
Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('/pages', "Admin\PagesController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/users', "Admin\UsersController", ['except' => ['show'], 'as' => 'admin']);
    // shop
    Route::resource('/products', "Admin\ProductsController", ['except' => ['show'], 'as' => 'admin']);
    Route::resource('/categories', "Admin\CategoriesController", ['except' => ['show'], 'as' => 'admin']);
});

// sign up
Route::get('/sign-up', "UsersController@signUp");
Route::post('/sign-up', "UsersController@store");

// sign in
Route::get('/sign-in', "LoginController@create")->name('login');
Route::post('/sign-in', "LoginController@store");
Route::delete('/logout', "LoginController@destroy");

Route::resource('products', "ProductsController", ['only' => ['index', 'show']]);
Route::resource('categories', "CategoriesController", ['only' => ['index', 'show']]);
Route::get('{page}', "PagesController@show")->name('pages.show');

resources/views/admin/partials/alert.blade.php
@if(Session::has('success'))
    <div class="alert alert-success mb-4 text-center" role="alert">
        {{ Session::get('success') }}
    </div>
@endif

resources/views/admin/partials/footer.blade.php
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://getbootstrap.com//docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
<script src="https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="https://getbootstrap.com/docs/4.5/examples/dashboard/dashboard.js"></script>

resources/views/admin/partials/head.blade.php
<!-- styles -->
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<style>
    body {
        font-family: 'Open Sans', sans-serif;
    }

    body * {
        outline: none;
    }

    .table td, .table th {
        vertical-align: middle;
    }

    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .admin-logout {
        background-color: transparent;
        border: none;
        box-shadow: none;
    }
</style>

<!-- Custom styles for this template -->
<link href="https://getbootstrap.com/docs/4.5/examples/dashboard/dashboard.css" rel="stylesheet">

resources/views/admin/partials/header.blade.php
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Dashboard</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <form action="/logout" method="post">
                @method('delete')
                @csrf
                <button type="submit" class="nav-link admin-logout">Sign out, <span class="text-white">{{Auth::user()->name}}</span></button>
            </form>
        </li>
    </ul>
</nav>

resources/views/admin/partials/sidebar.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.dashboard') }}">
                    <span data-feather="home"></span> Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.pages.index') }}">
                    <span data-feather="layers"></span> Pages
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.users.index') }}">
                    <span data-feather="users"></span> Users
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Shop</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.products.index') }}">
                    <span data-feather="shopping-cart"></span> Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.categories.index') }}">
                    <span data-feather="file-text"></span> Categories
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Orders
                </a>
            </li>
        </ul>
    </div>
</nav>